### ISSUE TITLE
Support for OpenBSD?

### ISSUE THREAD

**Issue by GMTSE** [rust-analyzer/rust-analyzer.github.io#193]
Hi,

I'm Using DoomEmacs under OpenBSD, it proposes, but fails to install "rustanalyzer" with error:
"/.../rust-analyzer.gz: unrecognized format"

When looking for more details, I found that the problem comes from the fact that the file size is 0b , which is related to the fact there is an automatic download process that compose the URL where to download based on the System's OS name, and this URL/file does not exists.

I triad to download the sources and compile them, but I had too much errors.

If someone can help make the code compile under (Open)BSD, that would be great!

**Comment by lnicola** [comment]
> I found that the problem comes from the fact that the file size is 0b , which is related to the fact there is an automatic download process that compose the URL where to download based on the System's OS name, and this URL/file does not exists.

That's a Doom Emacs bug, it should recognize that the URL doesn't exist. Consider reporting it there.

> I triad to download the sources and compile them, but I had too much errors.

Building from source should work if you have a recent enough compiler. Which `rustc` version are you on and/or what do those errors look like?

But keep in mind that in order for RA to be useful, you'll need the standard library source code (`rust-src`). Since `rustup` doesn't (didn't?) support OpenBSD, you'll need to extract that from the installation package for another platform.

PS: this is the repository for the rust-analyzer.github.io web site. Please use https://github.com/rust-lang/rust-analyzer in the future.

**Comment by lnicola** [comment]
No feedback and probably a downstream issue, closing.
