### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer.github.io#23]
I think the website would profit from branding, especially a logo. I'd like to help out with that, if that's okay. I already had a few ideas about a logo, which [I uploaded here](http://aloso.bplaced.net/ra/).

**Comment by matklad** [comment]
Those look cool! I like the first one, and the one that plays with `.` and completion. I am not sure about the general idea of just using `ra` for the logo: seems hard to decode into `rust-analyzer`. What do you think about taking the `.` idea further, and basically show completion:

![image](https://user-images.githubusercontent.com/1711539/72349847-95602580-36dd-11ea-8018-51d88ea9fa3d.png)

![image](https://user-images.githubusercontent.com/1711539/72349914-b6287b00-36dd-11ea-9bf6-c51f52ea5996.png)

?

**Comment by matklad** [comment]
I am also willing to be convinced that, for a logo, `ra` is better then the full `rust-analyzer`: basically, I have zero expertise here, and will trust your opinion :D

**Comment by MikailBag** [comment]
@matkald image no.2 from your post is too "VSCody".
User can deduce that only vscode is supported.

**Comment by matklad** [comment]
I'd say that the only VSCody thing there is the cube(?) icon. If we remove it, it'll actually look more like Emacs, due to pale fire theme and block cursor :) And it's easy to make it more neutral:

![image](https://user-images.githubusercontent.com/1711539/72351285-597a8f80-36e0-11ea-839c-2e3502f1cf63.png)

I am not sure if the font is right though... Should we use something sturdier, like the one from the website?

![image](https://user-images.githubusercontent.com/1711539/72351579-e887a780-36e0-11ea-8db9-d4ab6b78c944.png)

**Comment by flodiebold** [comment]
I like the completion idea (and the first font variant more than the second) :slightly_smiling_face:

**Comment by Aloso** [comment]
The first font is also used for the headlines on rust-lang.org.

**Comment by Aloso** [comment]
The brown color is supposed to look rusty, but a more pleasant, vibrant color might be better.

I'm not a professional designer, so don't trust me blindly :)

**Comment by Aloso** [comment]
@matklad I added two more logo ideas to the website, which show the whole name "rust analyzer".

> Should we use something sturdier, like the one from the website?

I thought that a monospace font would be more fitting for autocompletion. But if you disagree, I can change it.

**Comment by matklad** [comment]
Yeah, I must say I really like the full completion version! Unless anyone has strong feelings otherwise, I suggest we pick it.

I am still not super thrilled about the font choice, mainly because the picture seems visually imbalanced, due to `analyzer` being a longer word. I wonder if ... we can just use both fonts?

![image](https://user-images.githubusercontent.com/1711539/72389225-2a880c00-3728-11ea-9d87-b85dfa649579.png)

That subjectively restores the balance, and also underlines, via "slab / mono" font rhyme, that rust-analyze *completes* the Rust experience. Was programming a wrong choice of a carrier for me? Should I have been honing my skills of [explaining ridiculously expensive logos](https://meduza.io/shapito/2019/11/15/u-peterburga-novyy-turisticheskiy-logotip-biryuzovoe-severnoe-solntse-s-nazvaniem-goroda-u-orla-voronezha-i-mahachkaly-est-varianty-poluchshe) instead?

**Comment by Matthias247** [comment]
I like the completion ones, the one with the lightbulb and `r::a`! `r#a` for whatever reason reminds me too much about C#. The one with the cube somehow makes me think it has something to do with crates.io (it could be a crate?) - but that's actually not the intended meaning.

From all the completion versions, my favorite is the full one with the non-bold `rust`.

**Comment by yerke** [comment]
I like the full completion one

**Comment by univerz** [comment]
> Should we use something sturdier, like the one from the website?

in my eyes, rust is definitely strong and bold :)

**Comment by matklad** [comment]
Ok, so looks like everyone except myself likes the single font variant, so let's pick it!

![image](https://user-images.githubusercontent.com/1711539/72430674-52608980-3793-11ea-9772-ea98c328474f.png)

Here's a 900x600 horribly cropped logo.

@Aloso could you make an svg out of that thing, so that we can easily embedd it everywhere?

**Comment by Aloso** [comment]
@matklad I will, when I have time.

If you want, I can make it bold (currently it uses the _normal_ and _medium_ weights).

**Comment by bjorn3** [comment]
I looked at the html of the website to see if I could find the url to that logo. It turns out that it is actually made with only html and css. :smile:

**Comment by matklad** [comment]
Hm, another problem with the logo is it's 3x1, which doesn't really mesh well the square format for the avatar.

I wonder if we should have a variant where the two words are aligned?

```
rust.
analyzer
```

rather than

```
rust.
     analyzer
```

**Comment by matklad** [comment]
Set the picture as twitter and github org logo. I like it very much, thank you so much for this, @Aloso!

**Comment by flodiebold** [comment]
Maybe we could use the `r.a` form for the square variant? :thinking:

**Comment by Aloso** [comment]
> another problem with the logo is it's 3x1

That's why initially used only initials – which are also easier to read on small sizes, like the favicon.

Here are the SVGs:

![rust analyzer](https://user-images.githubusercontent.com/15658558/72436695-57c4d080-37a1-11ea-9bd1-29847695f36e.png)

![ra](https://user-images.githubusercontent.com/15658558/72436749-79be5300-37a1-11ea-889b-bbc469e2375e.png)

**Comment by matklad** [comment]
Ok, pngs are here: https://github.com/rust-analyzer/rust-analyzer/issues/567#issuecomment-574688752

Now we need to actually add the logo to the website :)

**Comment by Aloso** [comment]
For future readers, the logos can be found here: https://github.com/rust-analyzer/rust-analyzer/tree/master/assets
