### ISSUE TITLE
Include extension version in changelog posts

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer.github.io#56]
Hello!

In your weekly "[Changelog](https://rust-analyzer.github.io/thisweek/2020/07/06/changelog-32.html)" posts (which I look forward to every Monday), would you consider adding the vscode extension version number?  For example, this week the extension version is `v0.2.232`, but I'm not sure how to derive that version from either the commit hash or the release name.  I think this would help users figure out if their vscode extension has been updated yet or not.

Thanks!

**Comment by lnicola** [comment]
The problem is that we're using a GitHub Actions run identifier for release versioning. We could try to guess the value, but it seems finicky (every once in a while we'll be wrong). So we could either stash the value somewhere and wait for it to appear, or switch to a more predictable versioning scheme (which is also not trivial).

**Comment by eminence** [comment]
Somewhere along the way, this has been implemented.  The latest [changelog](https://rust-analyzer.github.io/thisweek/2023/02/06/changelog-167.html) clearly indicates the extension version `0.3.1394`, so I'm closing this issue as Done 🎉

**Comment by lnicola** [comment]
Yeah, they're being added manually. You can keep an eye on https://github.com/rust-lang/rust-analyzer/issues/13967, though.
